#!/bin/zsh -e

export RPC_URL=""
export ETHERSCAN_API_KEY=""
export API_URL="https://api.etherscan.io/api?"

eth=(
  "" # proxyAdmin
  "" # crossChainController
  "" # crossChainControllerImpl
  "" # ccipAdapter
  "" # hlAdapter
  "" # lzAdapter
  "" # wormholeAdapter
)

for address in $eth; do
  export CONTRACT=$address
  yarn run tsx scripts/verify-bytecode.ts
done

export RPC_URL=""
export ETHERSCAN_API_KEY=""
export API_URL="https://api.bscscan.com/api?"

bnb=(
  "" # proxyAdmin
  "" # crossChainController
  "" # crossChainControllerImpl
  "" # crossChainExecutor
  "" # ccipAdapter
  "" # hlAdapter
  "" # lzAdapter
  "" # wormholeAdapter
)

for address in $bnb; do
  export CONTRACT=$address
  yarn run tsx scripts/verify-bytecode.ts
done
